# ensure you are using the brew installed versions
# make sure /usr/local/bin is before /usr/sbin in your PATH
PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"

# OSX scripts path
export SCRIPTS="$(dirname $0)/bin"

# export PATH last
export PATH="$SCRIPTS:$PATH"
