load() {
	local zshrc=$DOTFILES/$1/zshrc

	[ -f $zshrc ] && source $zshrc
}

# Load OS specific configuration
case "$(get_os_name)" in
  darwin) load darwin;;
  *) load linux;;
esac

# Load config and plugins
for file in $DOTFILES/zsh/**/*.zsh; do
  source $file
done
